### ISSUE TITLE
外部接口情况汇总

### ISSUE THREAD

**Issue by balanceTWK** [balanceTWK/dap-stm32f103#2]
做成邮票孔的形式

| **接口** | **使用引脚** |               **备注**                |
| :------------------------- | :----------: | :-----------------------------------: |
| USB 接口   |    PA11 ；PA12    |  D+使用 PA11 ； D- 使用 PA12   |
| SWD 接口   |    PB0 ；PB13；PB12；PB14    |  NSRSET 使用 PB0；SWCLK 使用 PB13；SWDIO 使用 PB14 PB12   |
| 虚拟串口接口   |    PA2 ；PA3    |  TX 使用 PA2 ； RX 使用 PA3  |
| LED   |    PB6 ；PA9    |  PB6 指示usb连接 ；PA9 指示 USB 的四种状态   |

JTAG 引脚将会预留引出

TDI PA2 TDO PA10

**Comment by balanceTWK** [comment]
目前不打算支持 JTAG 接口，ARM 官方提供的 源码中 JTAG 的 GPIO 翻转函数都只实现了一个空函数。

```c
/** TDI I/O pin: Get Input.
\return Current status of the TDI DAP hardware I/O pin.
*/
static __forceinline uint32_t PIN_TDI_IN(void)
{
    return (0);   // Not available
}

/** TDI I/O pin: Set Output.
\param bit Output value for the TDI DAP hardware I/O pin.
*/
static __forceinline void PIN_TDI_OUT(uint32_t bit)
{
    ;             // Not available
}


// TDO Pin I/O ---------------------------------------------

/** TDO I/O pin: Get Input.
\return Current status of the TDO DAP hardware I/O pin.
*/
static __forceinline uint32_t PIN_TDO_IN(void)
{
    return (0);   // Not available
}


// nTRST Pin I/O -------------------------------------------

/** nTRST I/O pin: Get Input.
\return Current status of the nTRST DAP hardware I/O pin.
*/
static __forceinline uint32_t PIN_nTRST_IN(void)
{
    return (0);   // Not available
}

/** nTRST I/O pin: Set Output.
\param bit JTAG TRST Test Reset pin status:
           - 0: issue a JTAG TRST Test Reset.
           - 1: release JTAG TRST Test Reset.
*/
static __forceinline void PIN_nTRST_OUT(uint32_t bit)
{
    ;             // Not available
}
```

翻了一些 DAPLink 项目的 issue ，感觉 JTAG 有坑，现采用的芯片的资源可能不够。所以暂时不实现。

**Comment by balanceTWK** [comment]
@lymzzyh @liu2guang @jiejieTop @Guozhanxin

**Comment by jiejieTop** [comment]
OK @balanceTWK

**Comment by zhdjet** [comment]
能不能实现串口ISP下载功能啊？另外电路图上有个COM的指示灯，在源码中并没有定义，官方为什么还要画出来呢？

**Comment by balanceTWK** [comment]
> 能不能实现串口ISP下载功能啊？另外电路图上有个COM的指示灯，在源码中并没有定义，官方为什么还要画出来呢？

@zhdjet  可以实现ISP功能，但是 daplink 有提供拖拽下载功能，所以ISP功能没有用(等移植成rtt，后期会去实现离线下载功能)。 led灯 不会在邮票孔版本上画出来。多余的引脚会全引出来的。

**Comment by zhdjet** [comment]
但是 daplink 有提供拖拽下载功能，
@balanceTWK 虽然官方有这个功能，但是只能一对一的用，不能one to all啊？

**Comment by zhdjet** [comment]
@balanceTWK 我已经把全功能版的PCB发出去打板去了，元件也在采购中，决定跟着您玩RT-DAPLINK了！

**Comment by balanceTWK** [comment]
> @balanceTWK 我已经把全功能版的PCB发出去打板去了，元件也在采购中，决定跟着您玩RT-DAPLINK了！

别。。。电路有问题，f103 的 USB D+ 需要 1.5k 上拉电阻。@zhdjet

**Comment by balanceTWK** [comment]
@zhdjet  给我你的联系方式，到时候免费寄给你一块好了。

**Comment by zhdjet** [comment]
好的，谢谢！我把联系方式发您这个邮箱吧。balancetwk@yeah.net，麻烦您注意查收一下。感谢。

**Comment by zhdjet** [comment]
@balanceTWK 大师，与之相关的KICAD的库文件能上传一下吗？谢谢！
